### ISSUE TITLE
When switching to barrel mode from any other mode, the FOV resets to 360

### ISSUE THREAD

**Issue by phileday** [phileday/whirligig-old-issues#4]
- When switching to barrel mode from any other mode, the FOV resets to 360, which it shouldn't. It should instead switch to the last number used.

**Comment by phileday** [comment]
This has already been fixed.

**Comment by cheater** [comment]
Which version has it been fixed in? it still exists in early access 4.787. Please reopen this :) Also probably a good idea to wait for a confirmation from the reporter before closing a bug, I can close it myself after confirming - this is to make sure that we don't end up closing bugs simply because they don't exist on our computer, but do exist on another person's.
